#!/bin/sh

bash /home/philipp/.fehbg &
bash /home/philipp/bin/lightsOn.sh &
bash /home/philipp/bin/xrandr_hotplug.sh &
(while true; do conky -c ~/.conkyrc; done) &
cairo-dock -o &
fbpanel &
volwheel &
xflux -l 51.341137 -g 6.851654 &
sleep 5 &&
pidgin &
btsync-gui &

