#!/bin/sh

bash ~/.fehbg &
bash ~/bin/lightsOn.sh &
(while true; do bash ~/bin/autorandr.sh; done) &
(while true; do conky -c ~/.conkyrc; done) &
(while true; do tp-battery-icon; done) &
cairo-dock -o &
tint2 &
(pulseaudio --start && volwheel) &
xflux -l 51.341137 -g 6.851654 &
(sleep 5 && pidgin) &

